app:
  jwtSecret: bilermanJWTSecretKey
  jwtExpirationInMs: 604800000

spring:
  application:
    name: bilerman
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bilerman
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
  jakson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bilermaninc@gmail.com
    password: aqdrvfwdjhznoeqe
    properties:
      mail:
        smtp:
          auth: true
          timeout: 8000
          writetimeout: 8000
          connectiontimeout: 8000
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


---

spring:
  profiles: dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: bilerman
    user: postgres
    password: root
    baseline-version: 5

app:
  url: http://localhost:3000
  file:
    upload-dir: /Users/talguulu/Personal/Projects/Temp/bilerman-files

server:
  port: 8080

---

spring:
  profiles: prod
  datasource:
    platform: postgres
    url: jdbc:postgresql://bilerman-prod.cbyiljxj7wrz.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: bilerman2020
  flyway:
    url: jdbc:postgresql://bilerman-prod.cbyiljxj7wrz.eu-central-1.rds.amazonaws.com:5432/
    schemas: bilerman
    user: postgres
    password: bilerman2020

app:
  url: http://bilerman.kg
  file:
    upload-dir: C:/Users/Administrator/Desktop/bilerman-files

server:
  port: 80
